General:
  no-permission: "&c You do not have permission!"
MOTD:
  Line-1: "&cLine 1"
  Line-2: "&aLine 2"
# The maximum players of the server.
Server-Maximum-Players:
  Modify: true
  Maximum-Players: 200
Join-Message:
  Join:
    enabledSound: false
    Sound: BLOCK_ANVIL_FALL
    Message: '&a%player_name% &7joined the game (%server_online%/24)'
  Leave:
    Message: '&c%player_name% &7left the game (%server_online%/24)'
features:
  staffchat:
    Enabled: "&a StaffChat Enabled"
    Disabled: "&c StaffChat Disabled"
    Actionbar-Enabled: "&a Staffchat Enabled"
    Actionbar-Disabled: "&c Staffchat Disabled"
    #Allows you to send a message to staffchat without using the toggle. Put the following character first to use.
    prefix: "!"
    # Placeholders are {NAME} and {MESSAGE}, for the name of the staff member speaking and the message they sent.
    message-format: "&f[&cStaff-Chat&f] {NAME}: {MESSAGE} "
    staffchat_permission: "staffchat.use"
  vanish:
    Enabled: "&aYou have been vanished"
    Disabled: "&cYou have been unvanished"
  clearchat:
    GlobalClear: "&c[&aServerName&c] &aChat has been cleared!"
    PersonalClear: "Your Chat has been cleared!"
#database:
 #enabled: false
    #Pick either MySQL or MongoDB
    #database_type: MySQL
    #host: ""
    #port: ""
    #database: ""
    #username: ""
    #password: ""