name: SurvivalEssentials
version: 1.0
main: com.sandwich.SurvivalEssentials
depend: [PlaceholderAPI]
loadbefore: [PlaceholderAPI]
commands:
  StaffChat:
    description: Allows staff to communicate.
    aliases:
    - sc
  vanish:
    description: You can vanish yourself and other players
    usage: /vanish
    aliases: [v]
  cc:
    description: Global Clear Chat
    usage: /<command>
    aliases: [chatclear, clearchat]
  ccme:
    description: Clear Chat for the sender
    usage: /<command>
  install:
    description: Install Needed Components
    usage: /<command>
  kick:
    description: Kick players
    usage: /<command>