name: SurvivalEssentials
version: 1.0
main: com.sandwich.SurvivalEssentials
depend: [PlaceholderAPI]
loadbefore: [PlaceholderAPI]
commands:
  StaffChat:
    description: Allows staff to communicate.
    aliases:
    - sc
  vanish:
    description: You can vanish yourself and other players
    usage: /vanish
    aliases: [v]
